[project]
name = "flytekit-uv"
version = "0.1.0"
description = "A flytekit plugin for ImageSpec with a UV backend."
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "flytekit>=1.16,<2",
    "setuptools>=80.9.0",
]
