name: Publish
on:
  release:
    types:
      - prereleased
      - released

jobs:
  build-wheel:
    name: Build package wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Set version and build wheel
        run: |
          uv version ${{ github.event.release.tag_name }}
          uv build --wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          retention-days: 1
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/flytekit-uv
    permissions:
      id-token: write
    steps:
      - name: Download dist wheel
        uses: actions/download-artifact@v4
      - name: Publish wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
